// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMGOrgHHIsUQ_miq0Wi59aGVchwcZ-8f8',
    appId: '1:1042025410982:web:c31af606ca7465d0671f67',
    messagingSenderId: '1042025410982',
    projectId: 'devmob-gestionbudgetaire-6bba1',
    authDomain: 'devmob-gestionbudgetaire-6bba1.firebaseapp.com',
    storageBucket: 'devmob-gestionbudgetaire-6bba1.firebasestorage.app',
    measurementId: 'G-9CPBD0B1EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1O52nhSB8vZYtAD5bj_c-S-JPZxCdg8A',
    appId: '1:1042025410982:android:35b28c700f61a300671f67',
    messagingSenderId: '1042025410982',
    projectId: 'devmob-gestionbudgetaire-6bba1',
    storageBucket: 'devmob-gestionbudgetaire-6bba1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVT-6O3hSDYur4BPJkMJMyM_43mL0JfGk',
    appId: '1:1042025410982:ios:55e6d5dd6631f619671f67',
    messagingSenderId: '1042025410982',
    projectId: 'devmob-gestionbudgetaire-6bba1',
    storageBucket: 'devmob-gestionbudgetaire-6bba1.firebasestorage.app',
    iosBundleId: 'com.example.devmobGestionbudgetaire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVT-6O3hSDYur4BPJkMJMyM_43mL0JfGk',
    appId: '1:1042025410982:ios:55e6d5dd6631f619671f67',
    messagingSenderId: '1042025410982',
    projectId: 'devmob-gestionbudgetaire-6bba1',
    storageBucket: 'devmob-gestionbudgetaire-6bba1.firebasestorage.app',
    iosBundleId: 'com.example.devmobGestionbudgetaire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMGOrgHHIsUQ_miq0Wi59aGVchwcZ-8f8',
    appId: '1:1042025410982:web:6ef2b1fc5b1f8b40671f67',
    messagingSenderId: '1042025410982',
    projectId: 'devmob-gestionbudgetaire-6bba1',
    authDomain: 'devmob-gestionbudgetaire-6bba1.firebaseapp.com',
    storageBucket: 'devmob-gestionbudgetaire-6bba1.firebasestorage.app',
    measurementId: 'G-ET727JHT5M',
  );
}
